matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: 3.6
  - os: osx
    osx_image: xcode10.2
    
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
       ./build.sh
    fi
